### ISSUE TITLE
[Backend] Implement Firebase Locations database

### ISSUE THREAD

**Issue by LexuBBAA** [Ryuushinzou/SmartCarCleaner#39]
**Feature request description**
Enable the Spring app to store its Locations' data in the remote Firebase Database.

**Solution**
Create Firebase Database connection in the Spring project to enable consumption of the remote Firebase Database.

**Alternatives**
N/A

**Extra notes**
For feasibility notes, check ticket #33.

**Comment by mgodza93** [comment]
won't use firebase anymore
